version: '3.8'

services:
  mysql_dev:
    restart: always
    build: mysql
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    env_file:
      - .env
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    networks:
      - mysql-compose-network
    depends_on:
      - mysql_dev

networks: 
  mysql-compose-network:
    driver: bridge

volumes:
  mysql-data: {}