CREATE TABLE `USERS` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`nickname` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(20) NOT NULL,
	`gender` CHAR(1) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `PROFILE_PHOTOS` (
    `id` INT NOT NULL AUTO_INCREMENT,
    file_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE `SUB_CATEGORIES` (
    `id` INT NOT NULL AUTO_INCREMENT,
    name_sub_category VARCHAR(255) NOT NULL,
    name_category VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `LISTINGS` (
    `id` INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    price DECIMAL(10,8),
    currency VARCHAR(50),
    subcategory_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subcategory_id) REFERENCES SUB_CATEGORIES(id),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `SUB_CATEGORY_PARAMETERS` (
    `id` INT NOT NULL AUTO_INCREMENT,
    subcategory_id INT ,
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (subcategory_id) REFERENCES SUB_CATEGORIES(id),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;