CREATE TABLE `USERS` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`nickname` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(20) NOT NULL,
	`gender` CHAR(1) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `PROFILE_PHOTOS` (
    `id` INT NOT NULL AUTO_INCREMENT,
    file_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE `SUB_CATEGORIES` (
    `id` INT NOT NULL AUTO_INCREMENT,
    name_sub_category VARCHAR(255) NOT NULL,
    name_category VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `LISTINGS` (
    `id` INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    price DECIMAL(10,8) NOT NULL,
    currency VARCHAR(50) NOT NULL,
    subcategory_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (subcategory_id) REFERENCES SUB_CATEGORIES(id),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `SUB_CATEGORY_PARAMETERS` (
    `id` INT NOT NULL AUTO_INCREMENT,
    subcategory_id INT ,
    name_parameter VARCHAR(255) NOT NULL,
    required TINYINT(1) NOT NULL DEFAULT 0,
    FOREIGN KEY (subcategory_id) REFERENCES SUB_CATEGORIES(id),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO shopcrypto_dev.SUB_CATEGORIES
(name_sub_category, name_category)
VALUES
('CARROS_VANS', 'VEICULOS'),
('MOTOS', 'VEICULOS'),
('BARCOS_AERONAVES', 'VEICULOS'),
('CAMINHOES', 'VEICULOS'),
('ONIBUS', 'VEICULOS'),
('PECAS_ACESSORIOS', 'VEICULOS'),

('APARTAMENTOS', 'IMOVEIS'),
('CASAS', 'IMOVEIS'),
('QUARTOS', 'IMOVEIS'),
('TERRENOS_SITIOS_FAZENDAS', 'IMOVEIS'),
('COMERCIO_INDUSTRIA', 'IMOVEIS'),
('TEMPORADA', 'IMOVEIS'),

('SMARTPHONES', 'TELEFONIA'),
('ACESSORIOS_CELULAR', 'TELEFONIA'),
('PECAS_CELULAR', 'TELEFONIA'),
('SMARTWATCHES', 'TELEFONIA'),
('OUTROS', 'TELEFONIA');

INSERT INTO shopcrypto_dev.SUB_CATEGORY_PARAMETERS (subcategory_id,name_parameter,required)
VALUES
('1','MARCA',1),('1','CAMBIO',0),('1','POTENCIA',0),('1','PORTAS',0),('1','COMBUSTIVEL',0),('1','COR',0),('1','DIRECAO',0),('1','TIPO_CARROCERIA',0),('1','PLACA',1),('1','KM',1),

('7','TIPO',1),('7','OPERACAO_VENDA_ALUGUEL',1),('7','QUARTOS',1),('7','BANHEIROS',0),('7','AREA',0),('7','VAGAS_GARAGEM',0),('7','BANHEIROS',0),('7','VALOR_CONDOMINIO',0),('7','VALOR_IPTU',0),

('13','MARCA',1),('13','MODELO',1),('13','CONDICAO',0),('13','MEMORIA_INTERNA',0),('13','COR',0),('13','SAUDE_BATERIA',0);